### PR TITLE
Unlock Pretender v3 resolution

### PR DESCRIPTION
**Pull request by dcyriller**

### CODE REVIEW

**Comment by dcyriller** [comment]
whoops https://github.com/rwjblue/ember-cli-pretender/pull/70 duplicates

**Comment by dcyriller** [comment]
This lets me think: we don't need this addon anymore whenever we're using `ember-cli-autoimport`.

@rwjblue does it make sense to add this note in the README?

**Comment by rwjblue** [comment]
Yep, absolutely! I'd even be game for adding a warning when we detect that `this.parent.dependencies()` includes `ember-auto-import`...

**Comment by dcyriller** [comment]
Her we go https://github.com/rwjblue/ember-cli-pretender/pull/72

**Pull request closed without merging**
