### PR TITLE
update pretender to ^0.12.0

### PR DESCRIPTION
**Pull request by kellyselden**

### CODE REVIEW

**Comment by kellyselden** [comment]
ping @rwjblue

**Comment by alexdiliberto** [comment]
@kellyselden I would bump this PR to `1.0.0`, which was released about 1 week ago, for API stability

**Comment by kellyselden** [comment]
@alexdiliberto Yeah I was going to tackle that after this, maybe moving it to npm while I'm at it.

**Comment by rwjblue** [comment]
Released in v0.6.0.

**Comment by kellyselden** [comment]
Thanks @rwjblue

**Pull request merged**
